"""Base schemas, roles, state models, and event protocols for the Multi-Agent Support Copilot."""

from __future__ import annotations
from dataclasses import asdict, dataclass, field
from enum import Enum
import time
from typing import Any, Callable, Coroutine


class AgentRole(str, Enum):
    """The specialized role of an agent in the support copilot team."""
    PLANNER = "planner"
    RETRIEVER = "retriever"
    SYNTHESIZER = "synthesizer"
    CRITIC = "critic"
    ORCHESTRATOR = "orchestrator"


@dataclass
class PlanStep:
    """A discrete tool invocation step decomposed by the Planner."""
    step_number: int
    action: str
    tool_name: str
    arguments: dict[str, Any]
    reason: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class ExecutionPlan:
    """A structured plan of investigation steps for a customer inquiry."""
    objective: str
    steps: list[PlanStep] = field(default_factory=list)
    rationale: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "objective": self.objective,
            "rationale": self.rationale,
            "steps": [s.to_dict() for s in self.steps],
        }


@dataclass
class EvidenceItem:
    """An empirical data point retrieved by the Retriever from AgentGuard tools."""
    step_number: int
    tool_name: str
    arguments: dict[str, Any]
    result: Any
    execution_time_ms: float
    status: str = "SUCCESS"
    error: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class EvidenceDossier:
    """The complete dossier of empirical facts retrieved for an inquiry."""
    items: list[EvidenceItem] = field(default_factory=list)
    summary: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "summary": self.summary,
            "items": [it.to_dict() for it in self.items],
        }

    def get_tool_result(self, tool_name: str) -> Any | None:
        """Find the most recent successful tool result by tool name."""
        for item in reversed(self.items):
            if item.tool_name == tool_name and item.status == "SUCCESS":
                return item.result
        return None


@dataclass
class DraftResponse:
    """A candidate customer-facing response prepared by the Synthesizer."""
    draft_text: str
    key_findings: list[str] = field(default_factory=list)
    cited_evidence: list[str] = field(default_factory=list)
    confidence_score: float = 0.95

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class CritiqueReport:
    """Audit report generated by the Critic assessing factual accuracy and policy compliance."""
    passed: bool
    factual_accuracy_score: float  # 0.0 to 1.0
    hallucinations: list[str] = field(default_factory=list)
    unsupported_claims: list[str] = field(default_factory=list)
    policy_compliance_notes: list[str] = field(default_factory=list)
    revision_guidance: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class AgentEvent:
    """Real-time event emitted during multi-agent orchestration for streaming inspection."""
    event_type: str
    agent_role: AgentRole
    message: str
    payload: dict[str, Any] = field(default_factory=dict)
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["agent_role"] = self.agent_role.value
        return data


EventHandler = Callable[[AgentEvent], Coroutine[Any, Any, None] | None]


@dataclass
class CopilotFinalResult:
    """The consolidated outcome of the multi-agent copilot investigation."""
    inquiry: str
    tenant_id: str
    customer_id: str | None
    plan: ExecutionPlan
    dossier: EvidenceDossier
    final_response: str
    critique: CritiqueReport
    revisions_count: int
    total_duration_ms: float
    trace_id: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "inquiry": self.inquiry,
            "tenant_id": self.tenant_id,
            "customer_id": self.customer_id,
            "plan": self.plan.to_dict(),
            "dossier": self.dossier.to_dict(),
            "final_response": self.final_response,
            "critique": self.critique.to_dict(),
            "revisions_count": self.revisions_count,
            "total_duration_ms": self.total_duration_ms,
            "trace_id": self.trace_id,
        }

